version: "3.8"

services:
  # Infrastructure Services

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # Memory optimization
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    networks:
      - pms-network
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 60000
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      # Memory optimization for low-resource machines
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms256m"
    networks:
      - pms-network
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 15
      start_period: 120s
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      placement:
        constraints:
          - node.role == manager

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_PID: Developer
      # Limit SQL Server memory usage
      MSSQL_MEMORY_LIMIT_MB: 1024
    networks:
      - pms-network
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-C", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  # Backend Microservices

  # Backend services start with 0 replicas - scaled up by pipeline after infrastructure is ready
  booking-service:
    image: amaleltelabany/pms-booking-service:latest
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      # Kafka Configuration
      Kafka__BootstrapServers: kafka:9092
      Kafka__ClientId: BookingService
      Kafka__Producer__Acks: All
      Kafka__Producer__MessageTimeoutMs: "10000"
      Kafka__Consumer__GroupId: BookingServiceGroup
      Kafka__Consumer__EnableAutoCommit: "true"
      Kafka__Consumer__AutoOffsetReset: Earliest
      Kafka__Consumer__SessionTimeoutMs: "45000"
      Kafka__Consumer__MaxPollIntervalMs: "300000"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PMS_Booking;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True;Connection Timeout=60;"
    networks:
      - pms-network
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

  invoice-service:
    image: amaleltelabany/pms-invoice-service:latest
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      # Kafka Configuration
      Kafka__BootstrapServers: kafka:9092
      Kafka__ClientId: InvoiceService
      Kafka__Producer__Acks: All
      Kafka__Producer__MessageTimeoutMs: "10000"
      Kafka__Consumer__GroupId: InvoiceServiceGroup
      Kafka__Consumer__EnableAutoCommit: "true"
      Kafka__Consumer__AutoOffsetReset: Earliest
      Kafka__Consumer__SessionTimeoutMs: "45000"
      Kafka__Consumer__MaxPollIntervalMs: "300000"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PMS_Invoice;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True;Connection Timeout=60;"
    networks:
      - pms-network
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

  site-service:
    image: amaleltelabany/pms-site-service:latest
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      # Kafka Configuration
      Kafka__BootstrapServers: kafka:9092
      Kafka__ClientId: SiteService
      Kafka__Producer__Acks: All
      Kafka__Producer__MessageTimeoutMs: "10000"
      Kafka__Consumer__GroupId: SiteServiceGroup
      Kafka__Consumer__EnableAutoCommit: "true"
      Kafka__Consumer__AutoOffsetReset: Earliest
      Kafka__Consumer__SessionTimeoutMs: "45000"
      Kafka__Consumer__MaxPollIntervalMs: "300000"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PMS_Site;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True;Connection Timeout=60;"
    networks:
      - pms-network
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

  # Frontend Applications

  admin-frontend:
    image: salmawaleedd/pms-admin-frontend:latest
    ports:
      - "4200:80"
    networks:
      - pms-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  parker-frontend:
    image: salmawaleedd/pms-parker-frontend:latest
    ports:
      - "4201:80"
    networks:
      - pms-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # ELK Stack - Logging and Monitoring

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # Reduced memory for low-resource machines
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    networks:
      - pms-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      - XPACK_MONITORING_ENABLED=false
      - PIPELINE_WORKERS=1
    command: logstash -e 'input { tcp { port => 5000 codec => json_lines } } output { elasticsearch { hosts => ["elasticsearch:9200"] index => "pms-logs-%{+YYYY.MM.dd}" } stdout { codec => rubydebug } }'
    networks:
      - pms-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - pms-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Monitoring

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: pms-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - pms-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Visualizer (optional - shows swarm cluster status)
  # NOTE: Using port 9080 to avoid conflict with Jenkins (8080)
  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "9080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pms-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  pms-network:
    driver: overlay
    attachable: true

volumes:
  sql_data:
  elasticsearch_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
