version: "3.8"

services:
  # Infrastructure Services

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pms-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - pms-network
    healthcheck:
      test: ["CMD", "/bin/kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_PID: Developer
    networks:
      - pms-network
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-C", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  # Backend Microservices

  booking-service:
    image: amaleltelabany/pms-booking-service:latest
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      Kafka__BootstrapServers: kafka:9092
      Kafka__ClientId: BookingService
      Kafka__Consumer__GroupId: BookingServiceGroup
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PMS_Booking;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True;"
    networks:
      - pms-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  invoice-service:
    image: amaleltelabany/pms-invoice-service:latest
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      Kafka__BootstrapServers: kafka:9092
      Kafka__ClientId: InvoiceService
      Kafka__Consumer__GroupId: InvoiceServiceGroup
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PMS_Invoice;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True;"
    networks:
      - pms-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  site-service:
    image: amaleltelabany/pms-site-service:latest
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      Kafka__BootstrapServers: kafka:9092
      Kafka__ClientId: SiteService
      Kafka__Consumer__GroupId: SiteServiceGroup
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PMS_Site;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True;"
    networks:
      - pms-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  # Frontend Applications

  admin-frontend:
    image: salmawaleedd/pms-admin-frontend:latest
    ports:
      - "4200:80"
    networks:
      - pms-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  parker-frontend:
    image: salmawaleedd/pms-parker-frontend:latest
    ports:
      - "4201:3000"
    networks:
      - pms-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # ELK Stack - Logging and Monitoring

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - pms-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      - XPACK_MONITORING_ENABLED=false
      - PIPELINE_WORKERS=1
    command: logstash -e 'input { tcp { port => 5000 codec => json_lines } } output { elasticsearch { hosts => ["elasticsearch:9200"] index => "pms-logs-%{+YYYY.MM.dd}" } stdout { codec => rubydebug } }'
    networks:
      - pms-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - pms-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Monitoring

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: pms-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - pms-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Visualizer (optional - shows swarm cluster status)
  # NOTE: Using port 9080 to avoid conflict with Jenkins (8080)
  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "9080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pms-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  pms-network:
    driver: overlay
    attachable: true

volumes:
  sql_data:
  elasticsearch_data:
