version: '3.8'

services:
  # Traffic Director
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"  # Single public port
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 2  # Two Nginx instances for high availability

  # Admin App (internal only)
  admin-frontend:
    image: salmawaleedd/pms-admin-frontend:latest
    # NO ports - hidden inside Swarm
    deploy:
      replicas: 2

  # Parker App (internal only)
  parker-frontend:
    image: salmawaleedd/pms-parker-frontend:latest
    # NO ports - hidden inside Swarm
    deploy:
      replicas: 2

networks:
  default:  # All services automatically connect
    driver: overlay
