version: '3.8'

services:
  admin-frontend:
    image: salmawaleedd/pms-admin-frontend:latest
    ports:
      - "4200:80"
    networks:
      - frontend-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  parker-frontend:
    image: salmawaleedd/pms-parker-frontend:latest
    ports:
      - "3000:80"
    networks:
      - frontend-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  frontend-net:
    driver: overlay
    attachable: true
